title: Ludwig Schneider
description: Innovative Software and ML/AI Engineer seeking a role as machine learning engineer in R\&D, with advanced proficiency in C/C++, CUDA, Python, and high-performance software development, and a demonstrated history creating ML/AI solutions.
show_downloads: false
google_analytics: false
theme: jekyll-theme-cayman
